import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const $ = id => document.getElementById(id);
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x8dbbd8);
scene.fog = new THREE.FogExp2(0x8dbbd8, 0.0017);
const camera = new THREE.PerspectiveCamera(68, innerWidth / innerHeight, 0.05, 1600);
const renderer = new THREE.WebGLRenderer({ antialias:true, powerPreference:'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.AgXToneMapping; renderer.toneMappingExposure = 1.15; renderer.outputColorSpace = THREE.SRGBColorSpace;
document.body.appendChild(renderer.domElement);
const clock = new THREE.Clock(), ray = new THREE.Raycaster(), loader = new GLTFLoader(), UP = new THREE.Vector3(0,1,0);
function tex(base,speck,count=1200,size=256){const c=document.createElement('canvas');c.width=c.height=size;const g=c.getContext('2d');g.fillStyle=base;g.fillRect(0,0,size,size);for(let i=0;i<count;i++){g.globalAlpha=.04+Math.random()*.16;g.fillStyle=speck;const s=1+Math.random()*3;g.fillRect(Math.random()*size,Math.random()*size,s,s)}g.globalAlpha=1;const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t}
const grassTex=tex('#3c743d','#183719');grassTex.repeat.set(38,38);const roadTex=tex('#292c30','#70757a');roadTex.repeat.set(22,22);const concreteTex=tex('#85898d','#d2d2d2');concreteTex.repeat.set(5,5);
const grassMat=new THREE.MeshStandardMaterial({map:grassTex,roughness:1}),roadMat=new THREE.MeshStandardMaterial({map:roadTex,roughness:.92,metalness:.03}),concreteMat=new THREE.MeshStandardMaterial({map:concreteTex,roughness:.82});
const metalMat=c=>new THREE.MeshPhysicalMaterial({color:c,roughness:.28,metalness:.82,clearcoat:.5,clearcoatRoughness:.12});
const hemi=new THREE.HemisphereLight(0xdff4ff,0x25331f,2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffefcf,4);sun.position.set(-180,260,120);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-360;sun.shadow.camera.right=360;sun.shadow.camera.top=360;sun.shadow.camera.bottom=-360;sun.shadow.camera.near=1;sun.shadow.camera.far=850;sun.shadow.bias=-.0002;scene.add(sun);const moon=new THREE.DirectionalLight(0x6f8fc9,.15);moon.position.set(120,180,-180);scene.add(moon);
const sky=new THREE.Mesh(new THREE.SphereGeometry(900,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x3c82b8)},bottom:{value:new THREE.Color(0xe4f2f6)}},vertexShader:'varying vec3 v;void main(){v=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 v;uniform vec3 top;uniform vec3 bottom;void main(){float h=pow(max(v.y,0.0),.55);gl_FragColor=vec4(mix(bottom,top,h),1.0);}'}));scene.add(sky);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(1400,1400),grassMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
function road(x,z,w,d,rot=0){const r=new THREE.Mesh(new THREE.PlaneGeometry(w,d),roadMat);r.rotation.x=-Math.PI/2;r.rotation.z=rot;r.position.set(x,.012,z);r.receiveShadow=true;scene.add(r);for(const off of [-(d/2+1.4),d/2+1.4]){const s=new THREE.Mesh(new THREE.PlaneGeometry(w,2.5),concreteMat);s.rotation.x=-Math.PI/2;s.rotation.z=rot;s.position.set(x,.02,z+off);scene.add(s)}const lm=new THREE.MeshBasicMaterial({color:0xd9bb54});for(let i=-Math.floor(w/24);i<=Math.floor(w/24);i++){const l=new THREE.Mesh(new THREE.PlaneGeometry(.13,5.5),lm);l.rotation.x=-Math.PI/2;l.rotation.z=rot;l.position.set(x+i*18,.021,z);scene.add(l)}}
road(0,0,900,28);road(0,0,28,900,Math.PI/2);road(0,-210,900,24);road(210,0,24,900,Math.PI/2);
const water=new THREE.Mesh(new THREE.PlaneGeometry(900,380),new THREE.MeshPhysicalMaterial({color:0x2c87aa,roughness:.16,metalness:.08,transmission:.08,transparent:true,opacity:.88}));water.rotation.x=-Math.PI/2;water.position.set(0,-.08,-500);scene.add(water);
const buildings=[];
function building(x,z,w,d,h,enterable=false){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.57,.08,.30+Math.random()*.2),roughness:.68,metalness:.08}));body.position.y=h/2;body.castShadow=true;body.receiveShadow=true;g.add(body);const floors=Math.max(2,Math.floor(h/3.6));const glass=new THREE.MeshPhysicalMaterial({color:0x91c6d8,roughness:.12,metalness:.35,emissive:0x10242c,emissiveIntensity:.22,clearcoat:.35});for(let f=1;f<floors;f++)for(let q=-1;q<=1;q++)for(const side of [-1,1]){const win=new THREE.Mesh(new THREE.PlaneGeometry(Math.max(.65,w*.14),1.05),glass);win.position.set(q*w*.28,f*3.15+.8,side*(d/2+.015));win.rotation.y=side===1?0:Math.PI;g.add(win)}if(enterable){const door=new THREE.Mesh(new THREE.BoxGeometry(1.4,2.4,.12),new THREE.MeshStandardMaterial({color:0x33241c,roughness:.75}));door.position.set(0,1.2,d/2+.08);g.add(door);g.userData.enterable=true;g.userData.interior=new THREE.Vector3(x,z+d/2+4)}g.position.set(x,0,z);scene.add(g);buildings.push(g);return g}
[[-120,-120,52,38,32,true],[0,-150,62,42,55,true],[130,-100,58,48,42,false],[-160,120,58,44,48,false],[40,130,50,62,68,true],[170,150,72,48,54,false],[-250,-60,48,48,35,false],[260,-170,55,42,62,false],[-280,190,60,52,46,true],[285,120,48,58,72,false],[0,260,75,45,52,true]].forEach(v=>building(...v));for(let i=0;i<34;i++){const x=(Math.random()-.5)*620,z=(Math.random()-.5)*620;if(Math.abs(x)<48||Math.abs(z)<48)continue;building(x,z,18+Math.random()*18,16+Math.random()*18,6+Math.random()*12,Math.random()<.18)}
for(let i=0;i<170;i++){const a=Math.random()*Math.PI*2,r=65+Math.random()*560,g=new THREE.Group();const tr=new THREE.Mesh(new THREE.CylinderGeometry(.16,.28,2.2,8),new THREE.MeshStandardMaterial({color:0x5b3a24,roughness:1}));tr.position.y=1.1;tr.castShadow=true;g.add(tr);const cr=new THREE.Mesh(new THREE.IcosahedronGeometry(2.1+Math.random()*1.6,1),new THREE.MeshStandardMaterial({color:0x245c30,roughness:.96}));cr.position.y=3.5;cr.castShadow=true;g.add(cr);g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(g)}
const vehicles=[];function makeCar(x,z,color,rot=0){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.35,.58,4.5),metalMat(color));body.position.y=.62;body.castShadow=true;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.78,.68,2.15),new THREE.MeshPhysicalMaterial({color:0x16252c,roughness:.12,metalness:.25,transmission:.05,transparent:true,opacity:.92}));cabin.position.set(0,1.05,-.1);cabin.castShadow=true;g.add(cabin);const wm=new THREE.MeshStandardMaterial({color:0x111315,roughness:.96});for(const sx of [-1.08,1.08])for(const sz of [-1.45,1.45]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.24,18),wm);w.rotation.z=Math.PI/2;w.position.set(sx,.38,sz);g.add(w)}g.position.set(x,0,z);g.rotation.y=rot;g.userData={drivable:true,speed:0};scene.add(g);vehicles.push(g)}for(let i=0;i<30;i++)makeCar((Math.random()-.5)*620,(Math.random()-.5)*620,[0x1e2b38,0x7c1f20,0xc9ced0,0x17375d,0x646d31,0x3c273d][i%6],Math.random()*Math.PI*2);let driving=null;
const player=new THREE.Group();player.position.set(0,0,40);scene.add(player);const fallback=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.45,.9,6,12),new THREE.MeshStandardMaterial({color:0x245bc4,roughness:.62}));body.position.y=1;body.castShadow=true;fallback.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,20,16),new THREE.MeshStandardMaterial({color:0xd29a73,roughness:.75}));head.position.y=1.9;head.castShadow=true;fallback.add(head);player.add(fallback);
let character=null,mixer=null,idleAction=null,walkAction=null,runAction=null,currentAction=null;function playAction(a){if(!a||currentAction===a)return;if(currentAction)currentAction.fadeOut(.18);a.reset().fadeIn(.18).play();currentAction=a}loader.load('https://threejs.org/examples/models/gltf/Soldier.glb',g=>{character=g.scene;character.scale.setScalar(1.02);character.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material?.isMeshStandardMaterial)o.material.roughness=.6}});player.add(character);fallback.visible=false;mixer=new THREE.AnimationMixer(character);const clips=g.animations;const find=n=>clips.find(c=>c.name.toLowerCase().includes(n));idleAction=mixer.clipAction(find('idle')||clips[0]);walkAction=mixer.clipAction(find('walk')||clips[0]);runAction=mixer.clipAction(find('run')||clips[0]);playAction(idleAction)},undefined,()=>msg('3D model unavailable - fallback character active'));
const weapon=new THREE.Group();const gunBody=new THREE.Mesh(new THREE.BoxGeometry(.2,.22,1.3),new THREE.MeshPhysicalMaterial({color:0x20252a,roughness:.25,metalness:.88,clearcoat:.35}));gunBody.position.set(.42,1.42,-.6);weapon.add(gunBody);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.78,16),new THREE.MeshPhysicalMaterial({color:0x111316,roughness:.2,metalness:.92}));barrel.rotation.x=Math.PI/2;barrel.position.set(.42,1.42,-1.6);weapon.add(barrel);player.add(weapon);
const npcs=[];function npc(x,z){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.8,5,10),new THREE.MeshStandardMaterial({color:0x7b2d35,roughness:.72}));b.position.y=1;const h=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),new THREE.MeshStandardMaterial({color:0xb77c58,roughness:.8}));h.position.y=1.82;g.add(b,h);g.position.set(x,0,z);g.userData={npc:true,dir:new THREE.Vector3(Math.random()-.5,0,Math.random()-.5).normalize(),timer:1+Math.random()*3};scene.add(g);npcs.push(g)}for(let i=0;i<20;i++)npc((Math.random()-.5)*520,(Math.random()-.5)*520);
const targets=[];function spawnTarget(){const t=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,2.2,24),new THREE.MeshStandardMaterial({color:0xd62f32,roughness:.5}));t.position.set((Math.random()-.5)*180,1.1,(Math.random()-.5)*180);t.userData.hp=100;t.castShadow=true;scene.add(t);targets.push(t)}for(let i=0;i<12;i++)spawnTarget();const loots=[];const lootMat=new THREE.MeshPhysicalMaterial({color:0xf4c542,emissive:0x5a3d00,emissiveIntensity:.55,roughness:.24,metalness:.45,clearcoat:.8});function loot(type){const o=new THREE.Mesh(new THREE.BoxGeometry(.55,.35,.55),lootMat);o.position.set((Math.random()-.5)*360,.35,(Math.random()-.5)*360);o.userData.loot=type;o.userData.weight=type==='armor'?18:type==='medkit'?8:4;o.castShadow=true;scene.add(o);loots.push(o)}for(let i=0;i<24;i++)loot(['medkit','armor','arAmmo','grenades'][Math.floor(Math.random()*4)]);
const rainCount=650,rainPos=new Float32Array(rainCount*3);for(let i=0;i<rainCount;i++){rainPos[i*3]=(Math.random()-.5)*900;rainPos[i*3+1]=Math.random()*220;rainPos[i*3+2]=(Math.random()-.5)*900}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xb8d9ef,size:.12,transparent:true,opacity:.55,depthWrite:false}));rain.visible=false;scene.add(rain);let weather='clear',weatherTimer=35;
const weapons=[{name:'AR',mag:30,reserve:120,damage:25,rate:100},{name:'SMG',mag:40,reserve:160,damage:18,rate:75},{name:'SHOTGUN',mag:8,reserve:48,damage:60,rate:650}];let wi=0,ammo=30,reserve=120,hp=100,kills=0,lastShot=0,shooting=false,ads=false,pitch=-.1,stance='stand',jumpQueued=false,mx=0,my=0,sprinting=false,dayTime=9.5;const keys={};const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;const inv={medkit:1,armor:0,grenades:1,arAmmo:90,weight:18,capacity:100};
function msg(s){$('message').textContent=s;$('message').style.display='block';clearTimeout(msg.t);msg.t=setTimeout(()=>$('message').style.display='none',1100)}function hud(){$('stats').textContent=`HP ${Math.round(hp)} · ${weapons[wi].name} ${ammo}/${reserve} · Kills ${kills}${driving?' · DRIVING':''}`}function reload(){const m=weapons[wi].mag,n=Math.min(m-ammo,reserve);ammo+=n;reserve-=n;hud();msg(n?'RELOADED':'NO AMMO')}
function shoot(){const w=weapons[wi],now=performance.now();if(now-lastShot<w.rate)return;if(ammo<=0){reload();return}lastShot=now;ammo--;ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects([...targets,...npcs],true);if(hits.length){let o=hits[0].object;while(o.parent&&!o.userData.hp&&!o.userData.npc)o=o.parent;if(o.userData.hp!==undefined){o.userData.hp-=w.damage;if(o.userData.hp<=0){scene.remove(o);targets.splice(targets.indexOf(o),1);kills++;msg('ELIMINATION +1');setTimeout(spawnTarget,900)}else msg('HIT')}else if(o.userData.npc){scene.remove(o);npcs.splice(npcs.indexOf(o),1);kills++;msg('NPC DOWN')}}hud()}
function pickup(){let best=null,dist=7;for(const o of loots){const d=o.position.distanceTo(player.position);if(d<dist){best=o;dist=d}}if(!best){msg('NO LOOT NEARBY');return}if(inv.weight+best.userData.weight>inv.capacity){msg('BACKPACK FULL');return}inv[best.userData.loot]=(inv[best.userData.loot]||0)+1;inv.weight+=best.userData.weight;scene.remove(best);loots.splice(loots.indexOf(best),1);msg('LOOT PICKED UP');renderBag()}
function interact(){if(driving){driving.userData.speed=0;player.position.copy(driving.position).add(new THREE.Vector3(2,0,0).applyAxisAngle(UP,driving.rotation.y));driving=null;player.visible=true;msg('LEFT VEHICLE');return}let car=null,cd=5;for(const v of vehicles){const d=v.position.distanceTo(player.position);if(d<cd){car=v;cd=d}}if(car){driving=car;player.position.copy(car.position);msg('VEHICLE ENTERED');return}let b=null,bd=8;for(const x of buildings){if(!x.userData.enterable)continue;const d=x.position.distanceTo(player.position);if(d<bd){b=x;bd=d}}if(b){player.position.copy(b.userData.interior);msg('BUILDING ENTERED');return}pickup()}
function renderBag(){$('invBody').innerHTML=[['medkit','Med Kit'],['armor','Armor'],['grenades','Grenades'],['arAmmo','AR Ammo']].map(([k,n])=>`<div class="item"><span>${n}: ${inv[k]||0}</span><button data-use="${k}">USE</button></div>`).join('')+`<div class="item"><span>Weapon: ${weapons[wi].name}</span><button id="switchGun">SWITCH</button></div>`;$('weight').textContent=`Weight ${inv.weight} / ${inv.capacity}`;$('invBody').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>use(b.dataset.use));$('switchGun').onclick=()=>{wi=(wi+1)%weapons.length;ammo=weapons[wi].mag;reserve=weapons[wi].reserve;hud();renderBag()}}
function use(k){if(!inv[k])return;if(k==='medkit'){hp=Math.min(100,hp+60);inv[k]--;inv.weight=Math.max(0,inv.weight-8)}else if(k==='armor'){hp=Math.min(100,hp+25);inv[k]--;inv.weight=Math.max(0,inv.weight-18)}else if(k==='arAmmo'){reserve+=inv[k]*30;inv.weight=Math.max(0,inv.weight-inv[k]*4);inv[k]=0}else{inv[k]--;inv.weight=Math.max(0,inv.weight-4)}hud();renderBag()}function toggleBag(){const x=$('inventory');x.hidden=!x.hidden;if(!x.hidden)renderBag()}$('closeBag').onclick=toggleBag;
function updatePlayer(dt){if(driving){const v=driving,accel=(keys.KeyW?18:0)-(keys.KeyS?22:0);v.userData.speed=THREE.MathUtils.clamp(v.userData.speed+accel*dt,-8,24);if(!keys.KeyW&&!keys.KeyS)v.userData.speed*=Math.pow(.05,dt);const steer=(keys.KeyA?-1:0)+(keys.KeyD?1:0);v.rotation.y-=steer*dt*(Math.abs(v.userData.speed)/12);const f=new THREE.Vector3(0,0,-1).applyAxisAngle(UP,v.rotation.y);v.position.addScaledVector(f,v.userData.speed*dt);v.position.x=THREE.MathUtils.clamp(v.position.x,-620,620);v.position.z=THREE.MathUtils.clamp(v.position.z,-620,620);player.position.copy(v.position);player.visible=false;camera.position.lerp(v.position.clone().add(new THREE.Vector3(0,4.8,9).applyAxisAngle(UP,v.rotation.y)),.08);camera.lookAt(v.position.clone().add(new THREE.Vector3(0,1.1,0)));return}player.visible=true;const d=new THREE.Vector3();if(keys.KeyW)d.z--;if(keys.KeyS)d.z++;if(keys.KeyA)d.x--;if(keys.KeyD)d.x++;d.x+=mx;d.z-=my;const moving=d.lengthSq()>.0001;if(moving){d.normalize();d.applyAxisAngle(UP,player.rotation.y);const speed=sprinting||keys.ShiftLeft?10:stance==='crouch'?3.5:6;player.position.addScaledVector(d,speed*dt);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,Math.atan2(d.x,d.z),Math.min(1,10*dt))}if((keys.Space||jumpQueued)&&player.position.y<=.01){player.userData.vy=8;jumpQueued=false}player.userData.vy=(player.userData.vy||0)-22*dt;player.position.y+=player.userData.vy*dt;if(player.position.y<0){player.position.y=0;player.userData.vy=0}player.position.x=THREE.MathUtils.clamp(player.position.x,-620,620);player.position.z=THREE.MathUtils.clamp(player.position.z,-620,620);if(mixer){const s=moving?(sprinting||keys.ShiftLeft?2:1):0;playAction(s>1.5?runAction:s>0?walkAction:idleAction);mixer.update(dt)}const h=stance==='crouch'?1.6:2.2,dist=ads?3.7:6.3;const off=new THREE.Vector3(0,h,dist).applyAxisAngle(new THREE.Vector3(1,0,0),-pitch).applyAxisAngle(UP,player.rotation.y);camera.position.lerp(player.position.clone().add(off),.09);const look=player.position.clone().add(new THREE.Vector3(0,1.25,0));look.add(new THREE.Vector3(0,0,-3.2).applyAxisAngle(UP,player.rotation.y));look.y+=Math.sin(pitch)*3.2;camera.lookAt(look)}
function updateNPCs(dt){for(const n of npcs){n.userData.timer-=dt;if(n.userData.timer<=0){n.userData.timer=1+Math.random()*3;n.userData.dir.set(Math.random()-.5,0,Math.random()-.5).normalize()}n.position.addScaledVector(n.userData.dir,dt*(1.2+Math.random()*1.3));if(Math.abs(n.position.x)>650||Math.abs(n.position.z)>650)n.userData.dir.multiplyScalar(-1)}}
function updateWorld(dt){dayTime=(dayTime+dt*.055)%24;const ang=dayTime/24*Math.PI*2,daylight=THREE.MathUtils.clamp(Math.sin(ang)+.18,0,1);sun.position.set(Math.cos(ang)*260,Math.max(30,Math.sin(ang)*300),Math.sin(ang)*180);sun.intensity=.25+daylight*3.8;hemi.intensity=.55+daylight*1.6;moon.intensity=.08+(1-daylight)*.65;const top=new THREE.Color(0x0b1738).lerp(new THREE.Color(0x3c82b8),daylight),bottom=new THREE.Color(0x1c2742).lerp(new THREE.Color(0xe4f2f6),daylight);sky.material.uniforms.top.value.copy(top);sky.material.uniforms.bottom.value.copy(bottom);const fc=new THREE.Color(0x101b35).lerp(new THREE.Color(0x8dbbd8),daylight);scene.fog.color.copy(fc);scene.background.copy(fc);weatherTimer-=dt;if(weatherTimer<=0){weatherTimer=35+Math.random()*35;weather=Math.random()<.42?'rain':'clear';rain.visible=weather==='rain';msg(weather==='rain'?'RAIN STARTED':'WEATHER CLEARED')}if(rain.visible){const p=rain.geometry.attributes.position;for(let i=0;i<rainCount;i++){let y=p.getY(i)-35*dt;if(y<0)y=180+Math.random()*60;p.setY(i,y)}p.needsUpdate=true}}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code>='Digit1'&&e.code<='Digit3'){wi=+e.code.at(-1)-1;ammo=weapons[wi].mag;reserve=weapons[wi].reserve;hud()}if(e.code==='KeyB')toggleBag();if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0)shooting=true});addEventListener('mouseup',e=>{if(e.button===0)shooting=false});renderer.domElement.addEventListener('click',()=>{if(!touch&&!document.pointerLockElement)renderer.domElement.requestPointerLock()});addEventListener('mousemove',e=>{if(document.pointerLockElement&&!driving){player.rotation.y-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0018,-1.15,.65)}});
function stick(e){const r=$('leftStick').getBoundingClientRect(),max=r.width*.34;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>max){x=x/l*max;y=y/l*max}mx=x/max;my=y/max;$('stickKnob').style.transform=`translate(${x}px,${y}px)`}function resetStick(){$('stickKnob').style.transform='translate(0,0)';mx=my=0}$('leftStick').addEventListener('pointerdown',e=>{$('leftStick').setPointerCapture(e.pointerId);stick(e)});$('leftStick').addEventListener('pointermove',stick);$('leftStick').addEventListener('pointerup',resetStick);$('leftStick').addEventListener('pointercancel',resetStick);let lid=null,lx=0,ly=0;$('lookZone').addEventListener('pointerdown',e=>{lid=e.pointerId;lx=e.clientX;ly=e.clientY;$('lookZone').setPointerCapture(e.pointerId)});$('lookZone').addEventListener('pointermove',e=>{if(e.pointerId!==lid||driving)return;player.rotation.y-=(e.clientX-lx)*.006;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.004,-1.15,.65);lx=e.clientX;ly=e.clientY});$('lookZone').addEventListener('pointerup',()=>lid=null);$('lookZone').addEventListener('pointercancel',()=>lid=null);const hold=(id,on,off)=>{const e=$(id);e.onpointerdown=x=>{on();x.preventDefault()};e.onpointerup=off;e.onpointercancel=off};hold('fire',()=>shooting=true,()=>shooting=false);hold('ads',()=>{ads=true;camera.fov=52;camera.updateProjectionMatrix()},()=>{ads=false;camera.fov=68;camera.updateProjectionMatrix()});$('jump').onpointerdown=()=>jumpQueued=true;$('reload').onpointerdown=reload;$('bag').onpointerdown=toggleBag;$('gun').onpointerdown=()=>{wi=(wi+1)%weapons.length;ammo=weapons[wi].mag;reserve=weapons[wi].reserve;hud()};$('stance').onpointerdown=()=>{stance=stance==='stand'?'crouch':'stand';$('stance').textContent=stance==='stand'?'CROUCH':'STAND'};
$('playBtn').onclick=()=>start();$('trainingBtn').onclick=()=>start('TRAINING');function start(mode='MATCH'){$('menu').style.display='none';$('hud').hidden=false;localStorage.setItem('BR3D_PLAYER_NAME',$('playerName').value||'Player');msg(`${mode} STARTED`);hud()}async function auth(){try{const c=await (await fetch('/auth/config')).json();if(c.googleClientId&&window.google?.accounts?.id){google.accounts.id.initialize({client_id:c.googleClientId,callback:async x=>{const r=await fetch('/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:x.credential})});const d=await r.json();if(d.user){$('playerName').value=d.user.name.slice(0,16);$('loginStatus').textContent='Logged in with Google'}}});google.accounts.id.renderButton($('googleLogin'),{theme:'filled_black',size:'large',width:320})}}catch(e){}}$('facebookLogin').onclick=()=>{if(!window.FB){msg('Facebook login not configured');return}FB.login(r=>{if(r.authResponse)$('loginStatus').textContent='Facebook login authorized'},{scope:'public_profile'})};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});function loop(){const dt=Math.min(clock.getDelta(),.05);updatePlayer(dt);updateNPCs(dt);updateWorld(dt);if(shooting&&!driving)shoot();for(const o of loots)o.rotation.y+=dt*1.5;hud();renderer.render(scene,camera)}renderer.setAnimationLoop(loop);auth();
